### ISSUE TITLE
Summary visualization range not updated after filtering

### ISSUE THREAD

**Issue by julianheinrich** [lineupjs/lineupjs#117]
* Release number or git hash: 3.1.7
 * Web browser version and OS: Firefox Quantum, 60.3.0esr (32-bit), Windows 7

### Steps to reproduce

 1. Open soccer stats demo https://lineup.js.org/app/#soccer
 2. Sort descending by age
 3. Filter out right footed players

### Observed behavior
 * Summary histogram for age shows maximum age is 38

### Expected behavior
 * after step 3., the new maximum age should be updated to 37

**Comment by sgratzl** [comment]
are you referring to:

![image](https://user-images.githubusercontent.com/4129778/49278043-f437f080-f483-11e8-8bbb-40ed70def58b.png)

and the `38` written there? if so there is a misunderstanding, since the `38` doesn't mean the maximum in the current subset but the maximum domain value which is used to map the bars from 'no bar' (0) to 'full bar' (1). If it would automatically adapt all the bars would have to change, which implies that an filtering operation can change the ranking in cases the column is used as a component of a weighted sum.

**Comment by julianheinrich** [comment]
Yes, I am referring to the summary histogram of the Age-column in this example.

Not sure I understand the case where a "column is used as a component of a weighted sum", but yes, I would assume that filtering (e.g. outliers) can change a ranking. If I don't want to include players that are right-footed in my analysis, and as a consequence the range of ages of all players changes (because right-footed players were the only ones of age 38), then why keep 38 as the maximum age? 

However, I realized that I can get the expected behaviour by restricting the Age column to 37 using the filter-option.
