### ISSUE TITLE
Broken "sort groups by..." for multiple sort criteria

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#161]
* Release number or git hash: 169bd48b482ab44c6c0e7d74a4aae2309754b2e5
 * Web browser version and OS: Chrome 75

### Steps to reproduce

I could not provide a sandbox link, as a sorting bug was fixed with bafe4823b96e565fa261c2e0e49839eb00585079 (after v4.0.0-alpha.11) and no alpha.12 is available (yet).

 1. Run `npm start` and open http://localhost:8080/aggregate.html
 1. Column _cat_ -> column menu -> _sort groups by..._ -> descending
 1. Column _cat2_ -> column menu -> _sort groups by..._ -> descending/ascending

### Observed behavior

![lineup-sort-groups](https://user-images.githubusercontent.com/5851088/59281420-8b69d600-8c67-11e9-84bf-feed87a5bfdc.gif)

Only the first group sorting is applied (in the example _cat_) and the second group sorting has no effect.

### Expected behavior

 * All group sort criteria should be considered

**Comment by sgratzl** [comment]
so far when group sorting by a categorical value it actually sorts by two criteria: the name of the most frequent group, and second its count. 

https://github.com/lineupjs/lineupjs/blob/1019f08034bbc64dba5a0f7a245e22dab2baa920/src/model/internalCategorical.ts#L101-L110

e.g. in builder3.html

![image](https://user-images.githubusercontent.com/4129778/74859556-3e212680-5315-11ea-9dbe-e4ad5aa1192d.png)

first criteria level: Cat, 2nd. Cat2

values by group: 
 1. c1,c2: 
   1. most frequent c1, count 8
   2. most frequent c2, count 8
 1. c1,c3:
   1. most frequent c1, count 8
   2. most frequent c2, count 8
 1. c1, c1
   1. most frequent c1, 12
   2. most frequent c1, 12

sorting asc it means: c1,c2 < c1,c1 since the group since of the first group sort criteria is smaller.

**Comment by thinkh** [comment]
Thanks for the explanation. 

What does _most frequent group_ mean in this case? Is it the size (number of items) of a group?

I think for the user it's very opaque what the group sorting criteria is. In my opinion we have the following options:

1. **Sort groups by category name only**: Pretty obvious, since it works the same as the item sorting hierarchy and the category name is what the user can see
   ![lineup-sort-items](https://user-images.githubusercontent.com/5851088/77326587-4c9a9d80-6d1a-11ea-93c1-da4142076ef0.gif)
2. **Sort groups by most frequent group**: Only visible to the user if the group name column is available. It needs to better communicated/displayed to the user.
3. **User choice**: Alternatively, we can also leave the choice to the user and add another radio button to the _sort groups by_ dialog with the options _category title_ (default) and _category size_. It could look similar to the group by dialog of a string column:
   ![grafik](https://user-images.githubusercontent.com/5851088/77329483-51f9e700-6d1e-11ea-9b74-6962fb20ca8d.png)

@sgratzl What do you think?

**Comment by thinkh** [comment]
After checking issue #109 it seems like these two issues are pretty similar.

@sgratzl You posted already a screenshot https://github.com/lineupjs/lineupjs/issues/109#issuecomment-451392409 which matches my feature request in the previous comment. Maybe we move the discussion to issue #109 and continue there.

I still owe you a comment there. 😃

**Comment by sgratzl** [comment]
In the end a simple compromise is to sort groups of categoricals by their most frequent category name only. Thus, in case it is used as a grouping criteria it behaves as expected when combined with another group sorting criteria
