### ISSUE TITLE
Question: how to instantiate a LineUp plot with initial options?

### ISSUE THREAD

**Issue by keller-mark** [lineupjs/lineupjs#305]
* Release number or git hash: 00cdf76
 * Web browser version and OS: FireFox, Mac

### Steps to reproduce

1. Try to use the vanilla JS lineupjs library and provide initial options.
2. It seems there are many ways to create a LineUp plot, but it is unclear which of these methods allow setting initial options and how to do so:

Basically, I want to create a lineUp plot, and set the rowHeight to remove scrollbars, hide the sidebar, and remove the default ranking column. I have tried setting options to a plain JS object, as I am not using TypeScript, but it does not seem to work.

```js
const options = {
    sidePanel: false,
    rowHeight: 20,
    defaultRanking: false
};
```

Then, I have tried the following:

- `const lineup = LineUpJS.asLineUp(el, data, options);` (it seems the third argument here is not meant for options, `cannot infer type of column`)
- `const lineup = new LineUpJS.LineUp(el, data, options);` (results in `TypeError: t.on is not a function`)
- `const lineup = LineUpJS.createLineUp(el, data, options);` (results in `TypeError: t.on is not a function`)

I cannot seem to find a solution in the TypeDoc documentation or the API documentation pages, and would appreciate any help with this. Thanks!

**Comment by keller-mark** [comment]
I would also like to set the min domain value to zero. Does this mean I also need to be using the `builder`?

**Comment by keller-mark** [comment]
Update: I think figured it out

```js
const lineupBuilder = LineUpJS.builder(data)
    .deriveColumns()
    .deriveColors()
    .defaultRanking(false);

for(let col of lineupBuilder.columns) {
    if(col.type == "number") {
        col.domain[0] = 0;
    }
}
            
const lineup = lineupBuilder.build(el);
lineup.options.rowHeight = 25;
lineup.panel.collapsed = true;
```

**Comment by sgratzl** [comment]
Hi,

yes the builder is the way to go. So, the start it great but then there are better options to achieve what you want. 

```ts
const lineupBuilder = LineUpJS.builder(data)
    .deriveColumns()
    .deriveColors()
    .defaultRanking(false);
```

re rowheight: https://lineup.js.org/master/docs/classes/_builder_databuilder_.databuilder.html#rowheight

```ts
lineupBuilder.rowHeight(25, 2); 
```

note: when it comes to the scrollbars the `next` version should have a fix for it. Otherwise you can also try to add the following css rule: `.lu {  line-height: normal; }`

re panel collapsing: https://lineup.js.org/master/docs/classes/_builder_databuilder_.databuilder.html#sidepanel

```ts
lineupBuilder.sidePanel(true, false);
```

re custom numeric domain: https://lineup.js.org/master/docs/modules/_builder_column_numbercolumnbuilder_.html#buildnumbercolumn

note: in the v3 version you will end up with two columns of the same type, in v4 you can just override them

```ts
lineupBuilder.column(LineUpJS.buildNumberColumn('??attr??', [0, Number.NaN]))
// replace ??attr?? with the attribute name e.g., (`row: {a: 5} -> attr = a`)
```

while the `deriveColumns` is great, you have a finer control with the `build*Column(` functions, like setting a specific label, setting the column width, ...

In general, a starting point is https://lineup.js.org/api for the API. There you can find the generated API doc for all the classes and the main page links to the most important ones.
