### ISSUE TITLE
Crash when using data with feature that has empty array values

### ISSUE THREAD

**Issue by Aystein** [lineupjs/lineupjs#399]
* Lineup 4.1.1
* Chrome on Windows

### Steps to reproduce

1. Use a dataset that has a feature with only empty array values, for example

```
[ { feature1: [], feature2: "some" }, { feature1: [], feature2: "random" }, { feature1: [], feature2: "data" }, ... ]
```

2. Load the data into LineUp (I used the example code for the cats example)

### Observed behavior
Error is thrown, application crashes
![image](https://user-images.githubusercontent.com/9071970/100075446-3bbda100-2e40-11eb-9e1f-816f182de46e.png)

### Expected behavior
Not showing the feature, or giving an error message

**Comment by thinkh** [comment]
I can confirm this bug. The empty arrays are converted to `null` (in line 276) which causes the error later.

https://github.com/lineupjs/lineupjs/blob/be5bc0cc444f51342985f49a592bf013d09fdcfe/src%2Fprovider%2Futils.ts#L272-L277

If I comment the empty check out (line 273-276) `v` remains an empty array. In this case no error is thrown and the result looks like this:

![grafik](https://user-images.githubusercontent.com/5851088/100077186-56911500-2e42-11eb-914f-99f867b1ae49.png)

The error can be also tested directly when using a dataset that contains `null` (instead of `[]`) directly:

```
[ { feature1: null, feature2: "some" }, { feature1: null, feature2: "random" }, { feature1: null, feature2: "data" }, ... ]
```
